Repository picnee/picnee_back, pull requests merged in 2024-12, with the labels that each got.

#48 Feat/28
  src/main/java/com/picnee/travel/domain/notification/dto/event/CommentLikeEvent.java
  src/main/java/com/picnee/travel/domain/notification/entity/Notification.java
  src/main/java/com/picnee/travel/domain/notification/entity/NotificationType.java
  src/main/java/com/picnee/travel/domain/notification/eventListener/NotificationEventListener.java
  src/main/java/com/picnee/travel/domain/notification/service/NotificationService.java
  src/main/java/com/picnee/travel/domain/postComment/service/PostCommentService.java
  src/main/java/com/picnee/travel/domain/userPostCommet/service/UserPostCommentService.java
  src/test/java/com/picnee/travel/domain/notification/service/NotificationServiceForTest.java
  src/test/java/com/picnee/travel/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/picnee/travel/domain/post/entity/CreateTestPost.java
Labels: 🔥 Feat, 🧪 test

#51 feat/47
  src/main/java/com/picnee/travel/domain/board/dto/res/BoardRes.java
  src/main/java/com/picnee/travel/domain/board/entity/BoardCategory.java
  src/main/java/com/picnee/travel/domain/board/entity/Region.java
  src/main/java/com/picnee/travel/domain/board/service/BoardService.java
  src/main/java/com/picnee/travel/global/exception/ErrorCode.java
  src/main/java/com/picnee/travel/global/oauth/OAuthAttributes.java
  src/test/java/com/picnee/travel/domain/post/entity/CreateTestPost.java
  src/test/java/com/picnee/travel/domain/post/service/PostServiceTest.java
Labels: 🔥 Feat

#54 fix/53
  src/main/java/com/picnee/travel/domain/post/repository/PostRepositoryImpl.java
Labels: 🪛 fix

#55 test/46
  src/main/java/com/picnee/travel/domain/postComment/exception/NotProvideCommentLikeException.java
  src/main/java/com/picnee/travel/domain/postComment/service/PostCommentService.java
  src/main/java/com/picnee/travel/global/exception/ErrorCode.java
  src/test/java/com/picnee/travel/domain/post/service/PostServiceTest.java
  src/test/java/com/picnee/travel/domain/postComment/service/PostCommentServiceTest.java
Labels: 🔥 Feat

#57 feat/56
  src/main/java/com/picnee/travel/api/PlaceController.java
  src/main/java/com/picnee/travel/api/in/PlaceApi.java
  src/main/java/com/picnee/travel/domain/place/dto/req/CreatePlaceReq.java
  src/main/java/com/picnee/travel/domain/place/dto/req/OpeningHours.java
  src/main/java/com/picnee/travel/domain/place/dto/req/OpeningHoursReq.java
  src/main/java/com/picnee/travel/domain/place/dto/req/Period.java
  src/main/java/com/picnee/travel/domain/place/dto/req/TimeInfo.java
  src/main/java/com/picnee/travel/domain/place/dto/res/FindPlaceRes.java
  src/main/java/com/picnee/travel/domain/place/entity/OpeningHours.java
  src/main/java/com/picnee/travel/domain/place/entity/Place.java
  src/main/java/com/picnee/travel/domain/place/repository/OpeningHoursRepository.java
  src/main/java/com/picnee/travel/domain/place/service/OpeningHoursService.java
  src/main/java/com/picnee/travel/domain/place/service/PlaceService.java
  src/main/resources/data.sql
Labels: 🔥 Feat

#61 feat/59
  src/main/java/com/picnee/travel/domain/place/dto/PlaceTypeWeight.java
  src/main/java/com/picnee/travel/domain/place/dto/req/CreatePlaceReq.java
  src/main/java/com/picnee/travel/domain/place/dto/res/FindPlaceRes.java
  src/main/java/com/picnee/travel/domain/place/dto/res/OpeningHoursRes.java
  src/main/java/com/picnee/travel/domain/place/entity/Place.java
  src/main/java/com/picnee/travel/domain/place/entity/PlaceType.java
  src/main/java/com/picnee/travel/domain/place/exception/NotFoundCategoryException.java
  src/main/resources/data.sql
Labels: 🔥 Feat

#62 feat/60
  src/main/java/com/picnee/travel/api/PostCommentController.java
  src/main/java/com/picnee/travel/api/PostController.java
  src/main/java/com/picnee/travel/api/in/PostApi.java
  src/main/java/com/picnee/travel/api/in/PostCommentApi.java
  src/main/java/com/picnee/travel/domain/post/exception/NotAuthException.java
  src/main/java/com/picnee/travel/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/picnee/travel/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/picnee/travel/domain/post/service/PostService.java
  src/main/java/com/picnee/travel/domain/postComment/dto/res/GetChildrenCommentRes.java
  src/main/java/com/picnee/travel/domain/postComment/dto/res/GetMyPostCommentRes.java
  src/main/java/com/picnee/travel/domain/postComment/entity/PostComment.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepository.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepositoryCustom.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepositoryImpl.java
  src/main/java/com/picnee/travel/domain/postComment/service/PostCommentService.java
  src/main/java/com/picnee/travel/global/exception/ErrorCode.java
  src/test/java/com/picnee/travel/domain/post/service/PostServiceTest.java
Labels: 🔥 Feat

#71 feat/69
  src/main/java/com/picnee/travel/domain/postComment/entity/PostComment.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepositoryCustom.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepositoryImpl.java
  src/main/java/com/picnee/travel/domain/postComment/service/PostCommentService.java
Labels: 🔥 Feat

#73 refactor/72
  src/main/java/com/picnee/travel/domain/post/dto/res/FindMyPostRes.java
  src/main/java/com/picnee/travel/domain/postComment/dto/res/GetMyPostCommentRes.java
Labels: 🏗️ refactor
