Repository picnee/picnee_back, pull requests merged in 2024-11, with the labels that each got.

#22 feat/21
  src/main/java/com/picnee/travel/api/UserController.java
  src/main/java/com/picnee/travel/api/in/UserApi.java
  src/main/java/com/picnee/travel/domain/user/exception/NotValidRefreshTokenException.java
  src/main/java/com/picnee/travel/domain/user/service/UserService.java
  src/main/java/com/picnee/travel/global/exception/ErrorCode.java
  src/main/java/com/picnee/travel/global/jwt/dto/req/RefreshReq.java
  src/main/java/com/picnee/travel/global/jwt/dto/res/AccessTokenRes.java
  src/main/java/com/picnee/travel/global/jwt/dto/res/JwtTokenRes.java
  src/main/java/com/picnee/travel/global/jwt/filter/JwtFilter.java
  src/main/java/com/picnee/travel/global/jwt/provider/TokenProvider.java
  src/main/java/com/picnee/travel/global/oauth/OAuth2UserSuccessHandler.java
Labels: 🔥 Feat

#24 Feat/14
  src/main/java/com/picnee/travel/api/PostCommentController.java
  src/main/java/com/picnee/travel/api/in/PostCommentApi.java
  src/main/java/com/picnee/travel/domain/post/dto/res/FindPostRes.java
  src/main/java/com/picnee/travel/domain/post/entity/Post.java
  src/main/java/com/picnee/travel/domain/post/service/PostService.java
  src/main/java/com/picnee/travel/domain/postComment/dto/req/CreatePostCommentReq.java
  src/main/java/com/picnee/travel/domain/postComment/dto/req/UpdatePostCommentReq.java
  src/main/java/com/picnee/travel/domain/postComment/dto/res/GetPostCommentRes.java
  src/main/java/com/picnee/travel/domain/postComment/entity/PostComment.java
  src/main/java/com/picnee/travel/domain/postComment/exception/NotFoundCommentException.java
  src/main/java/com/picnee/travel/domain/postComment/exception/NotValidOwnerException.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepository.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepositoryCustom.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepositoryImpl.java
  src/main/java/com/picnee/travel/domain/postComment/service/PostCommentService.java
  src/main/java/com/picnee/travel/global/exception/ErrorCode.java
  src/main/resources/data.sql
Labels: 🔥 Feat

#23 feat/18
  src/main/java/com/picnee/travel/api/NotificationController.java
  src/main/java/com/picnee/travel/api/in/NotificationApi.java
  src/main/java/com/picnee/travel/domain/notification/dto/event/NotificationEvent.java
  src/main/java/com/picnee/travel/domain/notification/dto/event/PostCommentEvent.java
  src/main/java/com/picnee/travel/domain/notification/dto/event/PostLikeEvent.java
  src/main/java/com/picnee/travel/domain/notification/dto/event/ReviewScoreEvent.java
  src/main/java/com/picnee/travel/domain/notification/dto/res/FindNotificationRes.java
  src/main/java/com/picnee/travel/domain/notification/entity/Notification.java
  src/main/java/com/picnee/travel/domain/notification/entity/NotificationType.java
  src/main/java/com/picnee/travel/domain/notification/eventListener/NotificationEventListener.java
  src/main/java/com/picnee/travel/domain/notification/exception/NotFoundNotificationException.java
  src/main/java/com/picnee/travel/domain/notification/exception/NotNotificationRecipientException.java
  src/main/java/com/picnee/travel/domain/notification/repository/NotificationRepository.java
  src/main/java/com/picnee/travel/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/picnee/travel/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/picnee/travel/domain/notification/service/NotificationService.java
  src/main/java/com/picnee/travel/domain/review/repository/ReviewRepository.java
  src/main/java/com/picnee/travel/domain/review/service/ReviewService.java
  src/main/java/com/picnee/travel/global/exception/ErrorCode.java
Labels: 🔥 Feat

#30 fix/29
  src/main/java/com/picnee/travel/api/NotificationController.java
  src/main/java/com/picnee/travel/api/in/NotificationApi.java
  src/main/java/com/picnee/travel/domain/notification/dto/res/FindNotificationRes.java
  src/main/java/com/picnee/travel/domain/notification/service/NotificationService.java
  src/main/resources/data.sql
Labels: 🪛 fix

#27 feat/26
  src/main/java/com/picnee/travel/api/PostCommentController.java
  src/main/java/com/picnee/travel/api/in/PostCommentApi.java
  src/main/java/com/picnee/travel/domain/post/entity/Post.java
  src/main/java/com/picnee/travel/domain/post/service/PostService.java
  src/main/java/com/picnee/travel/domain/postComment/dto/req/CreatePostCommentReq.java
  src/main/java/com/picnee/travel/domain/postComment/dto/res/GetChildrenCommentRes.java
  src/main/java/com/picnee/travel/domain/postComment/dto/res/GetPostCommentRes.java
  src/main/java/com/picnee/travel/domain/postComment/repository/PostCommentRepositoryImpl.java
  src/main/java/com/picnee/travel/domain/postComment/service/PostCommentService.java
Labels: 🔥 Feat

#32 feat/31
  src/main/java/com/picnee/travel/api/UserController.java
  src/main/java/com/picnee/travel/api/in/UserApi.java
  src/main/java/com/picnee/travel/domain/user/dto/req/CreateUserReq.java
  src/main/java/com/picnee/travel/domain/user/dto/req/UpdateUserNicknameReq.java
  src/main/java/com/picnee/travel/domain/user/entity/User.java
  src/main/java/com/picnee/travel/domain/user/exception/NotProvideOAuthException.java
  src/main/java/com/picnee/travel/domain/user/repository/UserRepository.java
  src/main/java/com/picnee/travel/domain/user/service/UserService.java
  src/main/java/com/picnee/travel/global/exception/ErrorCode.java
  src/main/java/com/picnee/travel/global/oauth/CustomOauth2UserService.java
  src/main/java/com/picnee/travel/global/oauth/OAuth2CustomUser.java
  src/main/java/com/picnee/travel/global/oauth/OAuth2UserSuccessHandler.java
  src/main/java/com/picnee/travel/global/oauth/OAuthAttributes.java
  src/main/java/com/picnee/travel/global/oauth/OAuthInfo.java
  src/main/resources/data.sql
Labels: 🔥 Feat

#34 feat/33
  src/main/java/com/picnee/travel/api/UserController.java
  src/main/java/com/picnee/travel/api/in/UserApi.java
  src/main/java/com/picnee/travel/domain/user/service/UserService.java
  src/main/java/com/picnee/travel/global/config/CorsConfig.java
  src/main/java/com/picnee/travel/global/oauth/OAuth2UserSuccessHandler.java
Labels: 🔥 Feat

#36 feat/35
  src/main/java/com/picnee/travel/api/TokenController.java
  src/main/java/com/picnee/travel/api/UserController.java
  src/main/java/com/picnee/travel/api/in/TokenApi.java
  src/main/java/com/picnee/travel/api/in/UserApi.java
  src/main/java/com/picnee/travel/domain/token/dto/CreateOauthToken.java
  src/main/java/com/picnee/travel/domain/token/service/TokenService.java
  src/main/java/com/picnee/travel/domain/user/dto/req/CreateUserReq.java
  src/main/java/com/picnee/travel/domain/user/service/UserService.java
  src/main/java/com/picnee/travel/global/jwt/properties/JwtProperties.java
  src/main/java/com/picnee/travel/global/jwt/provider/TokenProvider.java
  src/main/java/com/picnee/travel/global/oauth/OAuth2UserSuccessHandler.java
  src/main/java/com/picnee/travel/global/oauth/OAuthAttributes.java
  src/main/java/com/picnee/travel/global/redis/service/RedisService.java
Labels: 🔥 Feat, 🏗️ refactor

#25 feat/15
  src/main/java/com/picnee/travel/api/LogController.java
  src/main/java/com/picnee/travel/api/in/LogAPI.java
  src/main/java/com/picnee/travel/domain/log/LogService.java
  src/main/java/com/picnee/travel/domain/log/dto/res/LogRes.java
Labels: 🔥 Feat

#40 feat/39
  src/main/java/com/picnee/travel/api/UserController.java
  src/main/java/com/picnee/travel/api/in/UserApi.java
  src/main/java/com/picnee/travel/domain/user/dto/res/CheckDuplicateRes.java
  src/main/java/com/picnee/travel/domain/user/repository/UserRepository.java
  src/main/java/com/picnee/travel/domain/user/service/UserService.java
Labels: 🔥 Feat

#42 test/19
  src/main/java/com/picnee/travel/domain/post/service/PostService.java
  src/main/java/com/picnee/travel/domain/usersPost/service/UsersPostService.java
  src/main/resources/application-test.yml
  src/main/resources/data.sql
  src/test/java/com/picnee/travel/domain/post/service/PostServiceTest.java
  src/test/java/com/picnee/travel/domain/user/entity/CreateTestUser.java
  src/test/java/com/picnee/travel/global/TestConfig.java
Labels: 🧪 test

#45 feat/44
  src/main/java/com/picnee/travel/api/PlaceController.java
  src/main/java/com/picnee/travel/api/in/PlaceApi.java
  src/main/java/com/picnee/travel/domain/place/dto/req/CreatePlaceReq.java
  src/main/java/com/picnee/travel/domain/place/dto/req/OpeningHours.java
  src/main/java/com/picnee/travel/domain/place/dto/req/Period.java
  src/main/java/com/picnee/travel/domain/place/dto/req/TimeInfo.java
  src/main/java/com/picnee/travel/domain/place/dto/res/FindPlaceRes.java
  src/main/java/com/picnee/travel/domain/place/entity/Place.java
  src/main/java/com/picnee/travel/domain/place/repository/PlaceRepository.java
  src/main/java/com/picnee/travel/domain/place/service/PlaceService.java
  src/main/resources/data.sql
Labels: 🔥 Feat
